component: scf
name: ws_demo_nodejs
inputs:
  name: ws_demo_nodejs
  src:
    src: ./src
  type: web
  protocolType: WS
  runtime: Nodejs12.16
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE