component: scf
name: ap-guangzhou_springboot_webfunc_java11
inputs:
  name: springboot_webfunc_java11
  src:
    src: ./src
  type: web
  runtime: Java11
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE