component: scf
name: ap-guangzhou_third-party_callback
inputs:
  name: Receive_third-party_callback_sample_function
  src:
    src: ./src
  type: web
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE