component: scf
name: ap-guangzhou_koa_demo
inputs:
  name: koa_demo
  src:
    src: ./src
  type: web
  runtime: Nodejs12.16
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE