component: scf
name: ap-guangzhou_default_audio_recorder
inputs:
  src:
    src: ./src
  region: ap-guangzhou
  name: SingleAudioRecorder
  runtime: Python3.6
  namespace: default
  handler: index.main_handler
  memorySize: 3072
  timeout: 43200
  asyncRunEnable: true
  traceEnable: true
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE