component: scf
name: ap-guangzhou_default_WordRecognition
inputs:
  name: WordRecognition
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE