component: scf
name: ap-guangzhou_default_SpringBoot
inputs:
  src:
    src: ./src
  region: ap-guangzhou
  name: SpringBoot
  runtime: Java8
  handler: com.tencent.scfspringbootjava8.ScfHandler::mainHandler
  memorySize: 512
  timeout: 30
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE