component: scf
name: ap-guangzhou_default_WordRecognition
inputs:
  name: WordRecognition
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  environment:
    - key: bucket_region
      value: bucket region
    - key: bucket_upload
      value: bucket name
  timeout: 10
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE
