component: scf
name: ap-guangzhou_helloworld_demo_php5
inputs:
  name: helloworld_demo_php5
  src:
    src: ./src
  type: web
  runtime: Php5
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE