component: scf
name: ap-guangzhou_httpdns_sdnshook
inputs:
  name: SDNSook
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: httpdns
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE