component: scf
name: ap-guangzhou_httpdns_sdnsHook
inputs:
  name: SDNSook
  src:
    src: ./src
  handler: index.main_handler
  runtime: Nodejs12.16
  namespace: httpdns
  region: ap-guangzhou
  memorySize: 1024
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: true
              enableExtranet: false
            qualifier: $DEFAULT
            authType: NONE