component: scf
name: ap-guangzhou_default_VideoSplice
inputs:
  asyncRunEnable: TRUE
  name: VideoSplice
  src:
    src: ./src
  runtime: Python3.7
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 3072
  timeout: 30
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE