component: scf
name: ap-guangzhou_HTTP_Forward_py3
inputs:
  name: HTTP_Forward_py3
  src:
    src: ./src
  type: web
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE