component: scf
name: ap-guangzhou_default_trtc
inputs:
  src:
    src: ./src
  region: ap-shanghai
  name: TRTC
  runtime: Java8
  handler: example.Hello::mainHandler
  memorySize: 1024
  timeout: 43200
  asyncRunEnable: true
  traceEnable: true
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE