component: scf
name: ap-guangzhou_java_webfunc_mockserver_demo
inputs:
  name: java_webfunc_mockserver_demo
  src:
    src: ./src
  type: web
  runtime: Java8
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  events:
      - http:
          parameters:
            name: url-trigger
            netConfig:
              enableIntranet: false
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE